### ISSUE TITLE
ESMO 2013 and ESMO 2016 should relax non-endometrioid condition

### ISSUE THREAD

**Issue by dchiu911** [TalhoukLab/EndoTools#10]
Based on the original esmo assignment functions in BC-665, the condition that checks for `hist_gr == "non-endometrioid"` should be relaxed to account for `"non-endometrioid or mixed"`. In the raw data packages this isn't an issue but when we combined variables from different sources we used "non-endometrioid or mixed" as the other group, before passing to the assignment functions.

**Comment by samuelcyleung** [comment]
yes, please kindly relax condition to "non-endometroid or mixed"
