### ISSUE TITLE
Use ER condition if available?

### ISSUE THREAD

**Issue by dchiu911** [TalhoukLab/EndoTools#2]
For assigning poorman's promise, we are currently using the following conditions:
```r
assign_risk_group <- function(grade,hist,mlh1,msh2,msh6,pms2,p53) {
  if (is.na(grade) || is.na(hist) || is.na(p53) || (is.na(msh6) | is.na(pms2))) {
    return(NA)
  }
  if (grade %in% c("grade 1","grade 2") &
      hist=="endometrioid" &
      #er%in%c("positive","weak, 1-50% of tumor nuclei","strong, +50% of tumor nuclei") &
      (msh6=="intact" & pms2=="intact" & (is.na(mlh1) || mlh1=="intact") & (is.na(msh2) || msh2=="intact")  ) &
      p53%in%c("wild type")) {
    return("low-risk")
  } else {
    return("high-risk")
  }
}
 ```

The cross canada cohort does not have ER scored, so it is not used in determining low risk. But say if we were trying to assign poorman's promise in Vancouver endometrial cohort, should we include the ER condition?

**Comment by samuelcyleung** [comment]
hi @dchiu911 , i think it really depends on the final poorman promise definition is.  My understanding is that it is still being refined?  I may be wrong.

So, if it is confirmed that ER should be part of the poorman's algorithm, than i think the function should return "unassignable" if ER is missing.

If it is optional, then perhaps, ER could be an optional parameter to the function and only check ER if it is available.

**Comment by dchiu911** [comment]
I just reviewed the manuscript and the final definition is as follows:

> In this study, we propose and retrospectively evaluate the prognostic value of an amended ProMisE classifier (ProMisE-), where MMR and p53 IHC is evaluated on all EC cases, and POLE mutational analysis only assessed in cases where adjuvant treatment may be considered; thus, cases fulfilling the following: grade 1 or 2, endometrioid histology, p53 normal, MMR proficient, with stage 1A and no lymphovascular space invasion, will be  labeled ‘very low-risk’ and POLE only evaluated  in the remaining tumours. 

Thus, I think safe to ignore ER and will add additional conditions for stage and LVSI (we created a post-surgical poorman's promise definition)
