### ISSUE TITLE
check for standardized vocabs in function

### ISSUE THREAD

**Issue by samuelcyleung** [TalhoukLab/EndoTools#3]
Thanks Derek for doing the function.

For all the functions, wondering would it be possible if you could please add logic such that it will prevent unexpected values from variable.

For example, currently, we assume that the ProMisE classes are called: MMRd, POLEmut, NSMP/p53wt, p53abn.

However, may be these will get changed in the future.  If so, i am not sure if the codes will return error or just return "unassignable"?

The same with other variables such as stage, myo.

I am working on a standardized vocab Excel that is on Teams: Clinical Informatics -> Data Dictionary -> Data Wish List_controlled vocab.xlsx.  Its far from complete and I plan to put is somewhere so that codes can lookup on the fly.  

Before this is ready, perhaps, can you just hard code controlled vocab values in the functions and return errors (e.g. use assertthat::assert_that) when unexpected values are encountered?

Happy to discuss and see what you think.

Many thanks.

Samuel

**Comment by dchiu911** [comment]
I agree data validation is needed to assist the user. We should throw error if fields are not standardized instead of returning a vector of NAs for "unassignable" cases due to misnamed inputs, and then prompt the user to fix/replace.

**Comment by dchiu911** [comment]
Function throws error and lists all the unexpected inputs:
```
with(emdb, assign_esmo2020(stage_full, grade_rev, hist_rev_gr, myo, lvi, eclass = p53))
Error: Invalid values in `eclass`: "wild type", "null", "abnormal", "cytoplasmic", "overexpression"
```
