### ISSUE TITLE
assign_esmo2020 - possible to have only one parameter for histotype?  i.e. either "hist" or "hist_gr"

### ISSUE THREAD

**Issue by samuelcyleung** [TalhoukLab/EndoTools#5]
Hi @dchiu911 , for the input parameter to esmo2020, since "hist_gr" is really a recoding of "hist", would it be possible if you could please kindly change to codes so that it only takes in one parameter for histotype.

I believe you can just use hist_gr since the algorithm only really cares if its endometrioid or not.  However, will need to watch out for CAH and benign cases (as these are possible values in "hist").  However, these cases likely won't have aggressive features (e.g. p53 mutation, myometrial invasion)

**Comment by dchiu911** [comment]
Hi @samuelcyleung I think the result of this is that esmo2020 without molecular class would have 0 advanced cases, because all stage III-IVA are captured in the high condition:
```r
      # high
      (stage %in% c("III", "IIIA", "IIIB", "IIIC", "IIIC1", "IIIC2", "IV", "IVA") & hist_gr == "endometrioid") |
        (stage == "IA" & grepl("non-endometrioid|mixed", hist_gr) & myo != "none") |
        (stage %in% c("I", "IB", "II", "IIA", "IIB", "III", "IIIA", "IIIB", "IIIC", "IIIC1", "IIIC2", "IV", "IVA") & grepl("non-endometrioid|mixed", hist_gr)) ~ VC.HIGH,
```
Does this look OK?
