### ISSUE TITLE
Add ACE-27

### ISSUE THREAD

**Issue by dchiu911** [TalhoukLab/EndoTools#9]
Hi @samuelcyleung I think we can add a function to assign ACE-27 based on the other 26 comorbidity variables. I see that only the conditions observed were coded into the database thus far, but I can add all conditions to a new function here, so long as we stick to the same nomenclature as the ACE table.

**Comment by samuelcyleung** [comment]
many thanks @dchiu911 .  I think its a great a idea.  The categories are specified in the controlled vocab excel file, so the nomenclature would be consistent.

**Comment by dchiu911** [comment]
hi @samuelcyleung I found two symptom descriptions  in the data that are slightly different from the source with the inequalities:

- ace_pad change to **>=6cm** for untreated abdominal aneurysm
- ace_htn change to **>=130mm Hg**

**Comment by dchiu911** [comment]
Will leave as is until a borderline case triggers further invsetigation

**Comment by samuelcyleung** [comment]
please leave as is.  Since function takes in categorical values, if/when border cases appear (i.e. =6cm and =130mm HG), will investigate.
